site_name: Pack 59 Den 6 Bears
nav:
  - Webelo: index.md
  - Bear: bear.md
  - Wolf: wolf.md
  - Tiger: tiger.md
  - Lion: lion.md
theme:
  name: null
  custom_dir: 'custom_theme/'
markdown_extensions:
  - markdown_captions
  - attr_list